version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install Deps
          command: ./scripts/install.sh
      - run:
          name: Sanity Check
          command: python3 scripts/sanity_check.py
      - run:
          name: Run Pytorch scripts
          command: ./scripts/run_pytorch.sh

workflows:
  version: 2
  workflow-build:
    jobs:
      - build
